### Promise.resolve 和 thenable

### 使用reject而不是throw
- Promise的构造函数，以及被 `then` 调用执行的函数基本上都可以认为是在 `try...catch` 代码块中执行的，所以在这些代码中即使使用 `throw` ，程序本身也不会因为异常而终止。
- 使用reject而不用throw是因为很难区分 `throw` 是我们主动抛出来的，还是因为真正的其它 **异常** 导致的
- 在 `then` 中使用reject的方法是在 .then(resolve)的 resolve函数里再返回一个promise, 通过这个promise来处理下一个.then函数是进入 reslove还是 reject


### 使用Promise进行顺序（sequence）处理

-   循环使用then调用的方法
-   使用for循环的方法
-   使用reduce的方法  ✅
-   分离出顺序处理函数的方法

